site_name: test_template
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: test_template
      handlers:
        python:
          options:
            docstring_style: numpy